### ISSUE TITLE
Gap between the FTS combo and its colorpicker

### ISSUE THREAD

**Issue by asaunier** [camptocamp/cgxp#1069]
When the colorpicker is enabled in the FullTextSearch plugin, a gap appears between the combo and the  colorpicker. See 
![c12c14a6-a7fa-11e5-980c-9961bd87527e](https://cloud.githubusercontent.com/assets/1192331/12206146/89f50468-b63f-11e5-86a4-2f454261e73f.png)

If one make a search, the closing button ("x") appears and fills the gap. After clicking the button, the combo expands to the right until the colorpicker and the gap disappears,

![c512ce48-a7fa-11e5-87c1-ccae9f1dcd5d](https://cloud.githubusercontent.com/assets/1192331/12206279/4db77f20-b640-11e5-8337-129b25b028b4.png)

According to dev inspectors the combo element actually "contains" the gap (as if the gap was reserved to place the closing button when needed). The input inside the element is narrower and eventually fills the full combo width only after clicking the closing button.

Anyone know if it's possible to make the input occupy the whole combo width at loading time, not only after the closing button is removed?

**Comment by eleu** [comment]
After discussion with @sbrunner : We don't see a solution with a reasonable effort for this issue. The problem is not the color field, but the size of the search field before searching and after searching (after clicking on the close button).

The issue should be solved in a newer GeoMapFish Version with NGeo.
